version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /utilities
  volumes:
    - .:/utilities:cached
    - ./node_modules:/utilities/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /utilities
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "13000:27017"

  manage:
    <<: *node
    image: danlynn/ember-cli:3.13.0
    working_dir: /utilities/services/manage
    entrypoint: ["ember"]
    command: ["serve", "--port", "13002"]
    tmpfs:
      - /utilities/services/manage/tmp
    ports:
      - "13002:13002"

volumes:
  mongodb: {}
  yarn-cache: {}
