version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-env-newrelic: &env-newrelic
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-mongo: &env-mongo
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
  ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}

x-node-defaults: &node
  tty: true
  init: true
  image: node:12
  entrypoint: ["node"]
  working_dir: /utilities
  volumes:
    - .:/utilities:cached
    - ./node_modules:/utilities/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /utilities
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "13000:27017"

  graphql:
    <<: *node
    working_dir: /utilities/services/graphql
    entrypoint: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      INTERNAL_PORT: 80
      EXTERNAL_PORT: 13001
    depends_on:
      - mongodb
    ports:
      - "13001:80"

  manage:
    <<: *node
    image: danlynn/ember-cli:3.13.0
    working_dir: /utilities/services/manage
    entrypoint: ["ember"]
    command: ["serve", "--port", "13002", "--proxy", "http://graphql"]
    tmpfs:
      - /utilities/services/manage/tmp
    depends_on:
      - graphql
    ports:
      - "13002:13002"

volumes:
  mongodb: {}
  yarn-cache: {}
